version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build

