version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@1.1.6
    steps:
      - checkout
      - run: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build

